[header]
name = "Yuchen Xue"
label = "M. Sc. Electrical Engineering"
introduction = "I have a strong background in deep learning, computer vision, and data engineering. I am passionate about applying my skills to solve real-world problems and contribute to innovative projects."
website = "https://yuchen-xue.com"

[header.picture]
# Insert your own profile picture for the CV
profile_picture_cv = "profile-picture-CV.jpg"
profile_picture_portfolio = "profile-picture-portfolio.jpg"

[header.contact]
residence = "Rostock, Germany"
email = "sean962081468@gmail.com"
# Use your own phone number
phone = "+49-1234-5678"

[[header.social_networks]]
url = "https://linkedin.com/in/sean-yuchen-xue"
display_text = "sean-yuchen-xue"
fa_icon = "linkedin"

[[header.social_networks]]
url = "https://github.com/yuchen-xue"
display_text = "yuchen-xue"
fa_icon = "github"

[[header.social_networks]]
url = "https://www.xing.com/profile/Yuchen_Xue2"
display_text = "Yuchen_Xue2"
fa_icon = "xing"

[[header.social_networks]]
url = "https://researchgate.net/profile/Yuchen-Xue-6"
display_text = "Yuchen-Xue-6"
fa_icon = "researchgate"

[sections]
[[sections.work_experience]]
company = "Fraunhofer IFF"
company_url = "https://www.iff.fraunhofer.de"
position = "Technical assistant"
location = "Magdeburg (Germany)"
start_date = "2023-05"
end_date = "2024-04"
summary = "I developed a deep learning-based zero-shot solution for industrial-level defect detection on different types of machine parts. This solution features accurate image segmentation of irregular machine parts using computer vision algorithms."
project_url = "https://drive.google.com/file/d/1IgSa0M2NDEWVdC4OKki5OhgfwNIk9P7o"
highlights = [
    "Development of an automatic point prompts generating technique for indicating machine parts in images",
    "Use of point prompts for assisting the process of mask generation",
    "Achieved 97.6% accuracy in the task of recognizing images with defected parts",
]
images = [
    {img_path = "portfolio_media/IFF-assembly-pairs-640x360.jpg", caption = "Camera views and CAD screenshots of one specific Air-Adapter"},
    {img_path = "portfolio_media/IFF-collecting-assembly-data-640x360.jpg", caption = "A turbine assembly is sent to a special rotary device for sampling"},
    {img_path = "portfolio_media/IFF-mask-overlay-640x360.jpg", caption = "Segmentation result of an Air-Adapter"}
]

[[sections.education]]
institution = "University of Rostock"
url = "https://www.uni-rostock.de"
study_program = "Master's program of Computational Electrical Engineering"
start_date = "2021-10"
location = "Rostock (Germany)"
highlights = ["Topics: Computational methods, Image processing"]

[[sections.education]]
institution = "University of Groningen"
url = "https://www.rug.nl"
study_program = "Exchange study under the Faculty of Science and Engineering"
start_date = "2020-02"
end_date = "2020-08"
location = "Groningen (the Netherlands)"
highlights = ["Topics: Parallel Computing, Scalable Computing"]

[[sections.education]]
institution = "National Taiwan University of Science and Technology"
url = "https://www.ntust.edu.tw"
study_program = "Master's program of Electrical Engineering"
start_date = "2017-09"
end_date = "2021-01"
location = "Taipei (Taiwan)"
highlights = [
    "Graduated as M. Sc. Electrical Engineering",
    "Master thesis: \"Survey on facial recognition models using deep learning technologies\"",
    "Topics: Deep Learning, Image processing, Data engineering",
]

[[sections.education]]
institution = "Thunhai University"
url = "https://www.thu.edu.tw"
study_program = "Bachelor's program of Electrical Engineering"
start_date = "2013-09"
end_date = "2017-06"
location = "Taipei (Taiwan)"
highlights = [
    "Graduated as B. Sc. Electrical Engineering",
    "Best bachelor project in the Department of Electrical Engineering of the year with the topic \"Self-navigable quadcopter based on Arduino and MultiWii\"",
    "Topics: Verilog HDL, Semiconductor, Microelectronics",
]

[[sections.keynote_technical_skills]]
label = "Programming Languages"
details = "Proficient with Python; good understanding with Java, C++ and R"

[[sections.keynote_technical_skills]]
label = "Machine Learning and Data Science Packages"
details = "Good understanding with computer vision, pattern matching, Pytorch, Tensorflow, OpenCV, Matplotlib, MySQL Server, Numpy, Pandas, Scikit Learn, Quarto"

[[sections.keynote_technical_skills]]
label = "Programming Frameworks and Tools"
details = "Good understanding with Docker Compose, Spring Framework, Git & Github, Linux, Bash, Raspberry Pi; Basic understanding with Arduino, Android Dev, VPN technologies WSL2 & VM and Verilog"

[[sections.language_skills]]
label = "English - Fluent (C1)"
details = "IETLS band 7 (CERF C1-Level). Date of the certification was issued: 26.03.2019"

[[sections.language_skills]]
label = "German - Fluent (C1)"
details = "CERF C1 Level. Issued by Sprachzentrum der Universtität Rostock on 19.02.2025."

[[sections.language_skills]]
label = "Chinese - Native speaker (C2)"
details = "Native Mandarin speaker"

[[sections.technical_projects."deep_learning_computer_vision"]]
title = "Master Thesis: \"Survey on Facial Recognition Models Using Deep Learning Technologies\""
start_date = "2019-10"
end_date = "2021-01"
location = "Taipei (Taiwan)"
summary = "This is an academic survey of different deep-learning based face recognition models, aiming at bringing insights to future researches in the field of deep learning."
highlights = [
    "Literal survey of different face recognition models",
    "Scientific analysis of the fundamental differences of selected solutions",
    "Use of experimental method for comparing the performance of selected models",
]
keywords = ["Face recognition", "deep learning", "PyTorch", "Tensorflow"]
external_links = [
    {url = "https://drive.google.com/file/d/15f7D6jnN9LGYLLqLOWl_LGaV0nfbShQ_", display_text = "Presentation slides"},
]
images = [
    {img_path = "portfolio_media/face-recognition-definition-640x360.jpg", caption = "A face recognition problem is defined as finding matching identities from gallery images"}, 
    {img_path = "portfolio_media/face-recognition-evaluation-640x360.jpg", caption = "Evaluation of the face recognition performance using ROC curve and AUC score"}
]

[[sections.technical_projects."deep_learning_computer_vision"]]
title = "Publication and Academic Speech with the Topic \"Improved Part-aligned Deep Features Learning for Person Re-Identification\""
start_date = "2018-07"
end_date = "2019-09"
location = "Taipei (Taiwan)"
summary = "This is a solution to the challenge of person re-identification (Re-ID) problem. The Re-ID problem is about recognizing and matching pedestrians with different appearances across different cameras."
highlights = [
    "Development of a solution to Re-ID problem with the help of computer vision and deep learning methods",
    "Contributed to a scientific paper, which was accepted by the 16th IEEE International Conference on Advanced Video and Signal-based Surveillance (AVSS)",
    "Delivered a workshop speech on this conference",
]
keywords = ["Cross-camera recognition", "Person Re-ID", "deep learning"]
external_links = [
    {url = "https://drive.google.com/file/d/19ZKLEMbkXMSyqFEvCcKnIaBZ6liYutBf", display_text = "Presentation slides"}
]
images = [
    {img_path = "portfolio_media/Re-id-definition-640x360.jpg", caption = "Illustration of a person re-identification problem"},
    {img_path = "portfolio_media/IPAF-architecture-640x360.jpg", caption = "Architecture of the proposed model"}
]

[[sections.technical_projects."deep_learning_computer_vision"]]
title = "Real-Time Detection of Pedestrians and Vehicles in Video Streams of Surveillance Cameras"
start_date = "2018-02"
end_date = "2018-04"
location = "Taipei (Taiwan)"
summary = "A deep learning based object detection solution for traffic monitoring inside the campus. Image data was manually collected, labelled and used for training a detector based on a pre-trained YOLOv3 model. The newly trained model shows significant improvement in our use case"
highlights = [
    "Improvement of 20% in precision compared to the base model",
    "Improvement on small, obscured, and overlapping objects",
    "Training of a reliable model with limited data using transfer learning technique",
]
keywords = [
    "C++",
    "Transfer learning",
    "Object detection",
]
external_links = [
    {url = "https://youtu.be/atY2ef5Eyfc", display_text = "Video demonstration"},
]
images = [
    {img_path = "https://i.imgur.com/XTuqJmK.gif", caption = "Detection result of the re-trained model"},
    {img_path = "https://i.imgur.com/IxPXNJb.gif", caption = "Detection result of the baseline model"}
]

[[sections.technical_projects."data_engineering"]]
title = "Energy Consumption Analysis of a Commercial Building Using a Generalized Additive Model"
start_date = "2018-04"
end_date = "2018-06"
location = "Taipei (Taiwan)"
summary = "This project, which serves as the final project of the course \"Regression Analysis\", is about the analysis and prediction of the energy consumption in an office building using a Generalized Additive Model (GAM). Data used in this project is originated from an open source dataset, namely \"EnerNOC GreenButton Data\"."
highlights = [
    "Implementation of a GAM model with high capability of generalization using R language",
    "The model exhibits a MAPE (mean absolute percentage error) value of 14.89 when predicting the energy consumption of the next two weeks",
    "Composing and hosting of a HTML report using R language, Quarto and Github Action",
]
keywords = [
    "R language",
    "Energy consumption analysis",
    "GAM",
]
external_links = [
    {url = "https://yuchen-xue.com/Learn-R-Quarto/content/linear-model/EnerNOC-GAM.html", display_text = "Online report"},
]
images = [
    {img_path = "https://yuchen-xue.com/Learn-R-Quarto/content/linear-model/EnerNOC-GAM_files/figure-html/unnamed-chunk-32-1.png", caption = "Prediction of the electricity consumption based on the dataset"}
]

[[sections.technical_projects."data_engineering"]]
title = "Online R Tutorial Website Based on Quarto"
start_date = "2024-09"
end_date = "2024-10"
location = "Rostock (Germany)"
summary = "This is a website that contains my study note and projects of R language."
highlights = [
    "Developed of a website using Quarto",
    "Automated deployment using Github Action",
]
keywords = ["Quarto", "R language", "Github Actions"]
url = "https://yuchen-xue.com/Learn-R-Quarto"

[[sections.technical_projects."software_development_embedded_systems"]]
title = "Web Application for Image Object Detection Based on Spring Framework"
start_date = "2018-01"
end_date = "2018-03"
location = "Taipei (Taiwan)"
summary = "A web application for hosting a deep learning based image object detection with the following function: a user can upload an image and download a new image with bounding boxes, with the detection result is stored in a database."
highlights = [
    "Implementation of the Spring Boot backend;",
    "Deployment of an object detection model using TensorFlow for Java;",
    "Implementation of MySQL database and Spring Database Connector for storing detection result.",
]
keywords = [
    "Spring framework",
    "SQL database",
    "Model deployment",
    "RESTful API",
]
external_links = [
    {url = "https://github.com/yuchen-xue/Spring-MySQL-TF-Detection", display_text = "Github repository"},
]
images = [
    {img_path = "https://i.imgur.com/CE9ElyB.gif", caption = "Demonstration of this web application"},
    {img_path = "portfolio_media/Springboot-detection-result-640x360.jpg", caption = "Example detection result"}
]

[[sections.technical_projects."software_development_embedded_systems"]]
title = "\"You Smile I Serve\" – A Concept of Smart Restaurant Based on Raspberry-Pi and Python"
start_date = "2018-03"
end_date = "2018-06"
location = "Taipei (Taiwan)"
summary = "This project is a prototype of an intelligent restaurant that provides a better customer experience when ordering. A customer is encouraged to smile to a camera to trigger a chatbot and can order their food by talking to this chatbot. A GUI was also developed for the restaurant owner to keep track of customer orders. The main components include a Raspberry Pi single board computer, a microphone, a webcam and a Pi-camera."
highlights = [
    "The design of the whole software and hardware structure",
    "Software implementation of smile detection and QR code reading",
    "Use of Google Cloud Platform API for implementing the voice recognition function",
    "Development of a user interface for managing customer's order",
]
keywords = ["Raspberry Pi", "OpenCV", "Cloud platform"]
external_links = [
    {url = "https://www.youtube.com/playlist?list=PLm7BNris7zlr3DjjrymRWPbd3Gzyv5SCB", display_text = "Video demonstration"},
]
images = [
    {img_path = "portfolio_media/YSIS-architecture-640x360.jpg", caption = "The architecture of the system"}
]

[[sections.technical_projects."software_development_embedded_systems"]]
title = "Bachelor Project: \"Self-Navigable Quadcopter based on Arduino and MultiWii\""
start_date = "2016-02"
end_date = "2016-06"
location = "Taichung (Taiwan)"
summary = "A collaborative project aims to build a quadcopter capable of navigating along a pre-defined route. This project won the best bachelor project of the Department of Electrical Engineering of Thunhai University during the year 2016."
highlights = [
    "Assemble of a quadcopter from hardware components, including a control board, motors, propeller, a frame and a battery",
    "Programming and testing of the control system",
    "Attempt of implementing a software program for the auto-piloting function",
]
keywords = ["Control system", "Unmanned aerial vehicle", "Arduino", "C"]
images = [
    {img_path = "portfolio_media/quadcopter-640x360.jpg", caption = "The fully-assembled quadcopter"},
    {img_path = "portfolio_media/quadcopter-controller-GUI-640x360.jpg", caption = "The user interface of the quadcopter controller"}
]

[[sections.publications]]
title = "Improved Part-aligned Deep Features Learning for Person Re-Identification"
authors = [
    "Sheng-Luen Chung",
    "Yuchen Xue",
    "Shih-Chao Chien",
    "Ruei-Shan Chan",
]
journal = "16th IEEE International Conference on Advanced Video and Signal Based Surveillance (AVSS)"
date = "2019-11-25"
page_number = "1-8"
publisher = "IEEE"
doi = "10.1109/AVSS.2019.8909867"

[[sections.publications]]
title = "Cloud Encryption Using Distributed Environmental Keys"
authors = [
    "Kun-Lin Tsai",
    "Fang-Yie Leu",
    "Yi-Fung Huang",
    "Chi Yang",
    "Cheng-Hsin Chang",
    "King-Shing Yip",
    "Yuchen Xue",
    "Guan-Chi Lai",
]
journal = "10th International Conference on Innovative Mobile and Internet Services in Ubiquitous Computing (IMIS)"
date = "2016-12-22"
page_number = "476-481"
publisher = "IEEE"
doi = "10.1109/IMIS.2016.73"

[[sections.miscellaneous]]
label = "Hobbies"
details = "Snowboarding, Hiking & trekking, Cycling, Badminton"

[[sections.miscellaneous]]
label = "Driving license"
details = "German driving license Class B"

[[sections.certificate_and_award]]
title = "Qualification Program -- Statistics Software R (advanced)"
date = "2024-09"
location = "Rostock (Germany)"
summary = "A 4-day workshop that features multiple theoretical topics and practical sessions related to multiple statistics topics, including linear model, anova, mean comparison with post-hoc tests, experimental designs and professional illustration"

[[sections.certificate_and_award]]
title = "The best annual final year project of the Department of Electrical Engineering"
date = "2016-08"
location = "Taichung (Taiwan)"
summary = "\"Self-Navigable Quadcopter based on Arduino and MultiWii\" was granted as the best annual final year project of the Department of Electrical Engineering at Thunhai University"

[[sections.certificate_and_award]]
title = "Calculus Competition at Thunghai University"
date = "2014-09"
location = "Taichung (Taiwan)"
summary = "Won a prize in the Calculus Competition held by the Department of Applied Mathematics at Thunhai University"

[[sections.volunteer_experiences]]
title = "Teaching assistant of practice sessions"
start_date = "2015-09"
end_date = "2017-06"
location = "Taipei and Taichung (Taiwan)"
summary = "I volunteered as a teaching assistant for three courses during my study at Thunghai University (Taichung, Taiwan) and National Taiwan University of Science and Technology (Taipei, Taiwan). My role was to introduce each assignment to the students, as well as to assist them during the practice session. Summary of these course:"
highlights = [
    "\"Logic Design Laboratory\" -- Verilog HDL language programming using FPGA",
    "\"Introduction to Cyber-Physical System\" -- Python programming on Raspberry Pi",
    "\"Regression Analysis\" -- Theory of linear regression model and practices of R language",
]
